environment:
  nodejs_version: "6"
  GH_TOKEN:
    secure: fyB6CRcrHbroxaBvzN6aPHUEhHGc3ljbbTPtEqruaDVe/iO8/dZn4LOVNS/fAlSX
  TESTOBJECT_E2E_TESTS: true
  matrix:
    - TESTOBJECT_PLATFORM_VERSION: 5
    - TESTOBJECT_PLATFORM_VERSION: 6
    - TESTOBJECT_PLATFORM_VERSION: 7.0
    - TESTOBJECT_PLATFORM_VERSION: 7.1
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run e2e

build: off
