environment:
  nodejs_version: "6"
  GH_TOKEN:
    secure: fyB6CRcrHbroxaBvzN6aPHUEhHGc3ljbbTPtEqruaDVe/iO8/dZn4LOVNS/fAlSX
  
  # Tells the NPM test script that we want to run the tests on TestObject, not locally
  TESTOBJECT_E2E_TESTS: true

  matrix:
    # The first build only builds and uploads the Appium staging zip and then exits out. This takes a long time and AppVeyor has a limit of 1h
    - FIRST_BUILD: true
      NPM_SCRIPT: e2e 

    # Break up tests to test different android versions and to run E2E tests in different groups to fit under the AppVeyor 1h limit
    - TESTOBJECT_PLATFORM_VERSION: 6
      NPM_SCRIPT: e2e:commands
    - TESTOBJECT_PLATFORM_VERSION: 6
      NPM_SCRIPT: e2e:find
    - TESTOBJECT_PLATFORM_VERSION: 6
      NPM_SCRIPT: e2e:keyboard
    - TESTOBJECT_PLATFORM_VERSION: 7
      NPM_SCRIPT: e2e:commands
    - TESTOBJECT_PLATFORM_VERSION: 7
      NPM_SCRIPT: e2e:find
    - TESTOBJECT_PLATFORM_VERSION: 7
      NPM_SCRIPT: e2e:keyboard

# Install NodeJS on Windows and install UiAutomator2 dependencies
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Build and run unit tests and a subgroup of the E2E tests
test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run %NPM_SCRIPT%

# Only run on PR's and master branch to spare TO servers
branches: 
  only:
  - master

# Don't run MSBUILD
build: off 
