environment:
  nodejs_version: "6"
  GH_TOKEN:
    secure: fyB6CRcrHbroxaBvzN6aPHUEhHGc3ljbbTPtEqruaDVe/iO8/dZn4LOVNS/fAlSX
  TESTOBJECT_E2E_TESTS: true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run e2e

build: off
