jobs:
  - job: UiAutomator2CI
    pool:
      vmImage: macOS-12
    variables:
      CI: true
      TERM: dumb
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 16.x
    - script: npm install
      displayName: Install Node dependencies
    - script: |
        npm install -g appium@next
        npm run build
      displayName: Build
    - script: npm test
      displayName: Run Unit Tests
