variables:
  DEFAULT_NODE_VERSION: 16.x
  DEFAULT_VM_IMAGE: macOS-latest

stages:
- stage: Unit_Tests_And_Linters
  jobs:
  - job: unit_tests
    pool:
      vmImage: $(DEFAULT_VM_IMAGE)
    variables:
      CI: true
      TERM: dumb
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(DEFAULT_NODE_VERSION)
    - script: npm install
      displayName: Build
    - script: npm run test
      displayName: Run Unit Tests

# TODO: Update e2e tests for webdriverio compatibility
- stage: Integration_Tests
  jobs:
  - template: templates/android-e2e-template.yml
    parameters:
      script: npm run e2e-test:driver
      sleep: 20
      name: sdk30_e2e_tests
      vmImage: $(DEFAULT_VM_IMAGE)
      CHROMEDRIVER_VERSION: 74.0.3729.6
      ANDROID_SDK_VERSION: 30
      ANDROID_FLAVOUR: google_apis
      ANDROID_ARCH: x86_64
      NODE_VERSION: $(DEFAULT_NODE_VERSION)
  - template: templates/android-e2e-template.yml
    parameters:
      script: npm run e2e-test:driver
      name: sdk28_e2e_tests
      vmImage: $(DEFAULT_VM_IMAGE)
      CHROMEDRIVER_VERSION: 2.44
      ANDROID_SDK_VERSION: 28
      NODE_VERSION: $(DEFAULT_NODE_VERSION)
  - template: templates/android-e2e-template.yml
    parameters:
      script: npm run e2e-test:driver
      name: sdk25_e2e_tests
      vmImage: $(DEFAULT_VM_IMAGE)
      CHROMEDRIVER_VERSION: 2.28
      ANDROID_SDK_VERSION: 25
      NODE_VERSION: $(DEFAULT_NODE_VERSION)
  - template: templates/android-e2e-template.yml
    parameters:
      script: npm run e2e-test:driver
      name: sdk23_e2e_tests
      vmImage: $(DEFAULT_VM_IMAGE)
      CHROMEDRIVER_VERSION: 2.20
      ANDROID_SDK_VERSION: 23
      NODE_VERSION: $(DEFAULT_NODE_VERSION)
